In [56]:
import numpy as np
import pandas as pd
import tensorly as tl
from tensorly import random

In [68]:
tensor_a = random.random_tensor((5,5,5))

In [69]:
tensor_a

array([[[0.83195596, 0.47596151, 0.71650061, 0.92384283, 0.02790548],
        [0.62231825, 0.69282128, 0.18858441, 0.29965281, 0.5190546 ],
        [0.98436109, 0.36392765, 0.7488802 , 0.50496296, 0.8662444 ],
        [0.27099731, 0.90401699, 0.73743917, 0.9276555 , 0.98664324],
        [0.3800217 , 0.00663959, 0.76958272, 0.41906234, 0.18151421]],

       [[0.1251875 , 0.77407513, 0.43114787, 0.36523488, 0.18125394],
        [0.40861145, 0.58176993, 0.57713268, 0.38403114, 0.37485575],
        [0.94540676, 0.70465207, 0.18919244, 0.24066466, 0.30928879],
        [0.4319512 , 0.48633876, 0.53144997, 0.42406995, 0.31906803],
        [0.2234392 , 0.93596664, 0.89598809, 0.09440968, 0.2538597 ]],

       [[0.23823704, 0.51396245, 0.23972942, 0.49055708, 0.21623763],
        [0.43163512, 0.84626351, 0.88230949, 0.76986272, 0.88584255],
        [0.60200663, 0.42161458, 0.40820894, 0.9067411 , 0.70226562],
        [0.52593061, 0.97458883, 0.77353732, 0.22392928, 0.62603871],
        [0.40315

In [88]:
from tensorly.decomposition import parafac
factors = parafac(tensor_a, rank=5)
len(factors)

2

In [89]:
factors

(weights, factors) : rank-5 CPTensor of shape (5, 5, 5)

In [90]:
factors[0]

array([1., 1., 1., 1., 1.])

In [91]:
factors[1]

[array([[ 3.22548408e+00,  7.16978545e-01, -4.89951879e-01,
          4.06172217e-01,  7.22734870e-01],
        [ 2.57884261e+00,  6.90691014e-04, -7.25289238e-02,
          1.03010345e-01,  3.93254276e-01],
        [ 2.91778447e+00,  5.71014609e-01,  1.32404260e-01,
          1.13404034e-01,  2.99492916e-01],
        [ 1.42814019e+00, -4.65260994e-01,  1.53638783e-01,
          2.08980011e-01,  9.06825312e-02],
        [ 2.05894273e+00,  5.03088955e-01,  6.22169874e-01,
          2.75803606e-02, -1.84197601e-01]]),
 array([[ 0.56632192,  0.03272059,  1.10611491, -3.48906305, -2.18334753],
        [ 0.4768073 , -0.39122394, -0.33776077, -1.41585794, -0.69623397],
        [ 0.21573708, -0.25760457, -1.2760392 , -0.97699202,  1.12037861],
        [ 0.57892326, -0.16578263,  1.06083415, -0.2480568 , -1.06736373],
        [ 0.65212499,  1.34512255,  0.91474142, -0.0462141 , -1.61164919]]),
 array([[ 0.47807394,  0.30778593, -0.70242274, -0.89781907,  1.09034076],
        [ 0.52423113, -0.8

In [92]:
A = factors[1][0]
B = factors[1][1]
C = factors[1][2]

In [93]:
C

array([[ 0.47807394,  0.30778593, -0.70242274, -0.89781907,  1.09034076],
       [ 0.52423113, -0.85261256, -0.35462992,  0.15149804,  0.28513177],
       [ 0.48169125,  0.10983279, -0.02524863, -0.03891896,  0.29064055],
       [ 0.39585432, -0.12225493, -0.96951174, -0.52837964,  0.65722744],
       [ 0.52455411, -0.55080401, -0.52162997,  0.06849261,  0.66407196]])

In [94]:
from tensorly.tenalg import khatri_rao
CB_khatri_rao = khatri_rao([C, B])
X_mode1 = tl.unfold(tensor_a, mode=0)
X_approx_mode1 = np.dot(A, CB_khatri_rao.T)

In [95]:
# print results

print("Original tensor (unfolded along mode-1):")
print(X_mode1)

print("\nApproximated tensor (unfolded along mode-1):")
print(X_approx_mode1)

Original tensor (unfolded along mode-1):
[[0.83195596 0.47596151 0.71650061 0.92384283 0.02790548 0.62231825
  0.69282128 0.18858441 0.29965281 0.5190546  0.98436109 0.36392765
  0.7488802  0.50496296 0.8662444  0.27099731 0.90401699 0.73743917
  0.9276555  0.98664324 0.3800217  0.00663959 0.76958272 0.41906234
  0.18151421]
 [0.1251875  0.77407513 0.43114787 0.36523488 0.18125394 0.40861145
  0.58176993 0.57713268 0.38403114 0.37485575 0.94540676 0.70465207
  0.18919244 0.24066466 0.30928879 0.4319512  0.48633876 0.53144997
  0.42406995 0.31906803 0.2234392  0.93596664 0.89598809 0.09440968
  0.2538597 ]
 [0.23823704 0.51396245 0.23972942 0.49055708 0.21623763 0.43163512
  0.84626351 0.88230949 0.76986272 0.88584255 0.60200663 0.42161458
  0.40820894 0.9067411  0.70226562 0.52593061 0.97458883 0.77353732
  0.22392928 0.62603871 0.40315032 0.01639737 0.85280756 0.16056728
  0.39965759]
 [0.68937586 0.08191338 0.24981507 0.3781363  0.27659612 0.65213633
  0.40301364 0.5300315  0.2758921

In [100]:
print("\nAre the original and approximated matricized tensors close?")
print(np.allclose(X_mode1, X_approx_mode1, rtol=1, atol=1))


Are the original and approximated matricized tensors close?
True
