In [1]:
import numpy as np
import pandas as pd
import tensorly as tl
from tensorly import random
import random
random.seed(42)

In [2]:
I = 10
J = 12
K = 14
tensor = tl.tensor(np.random.random((I, J, K)))

In [3]:
tensor

array([[[0.23970169, 0.72498048, 0.20989424, ..., 0.88032819,
         0.84417747, 0.7937663 ],
        [0.29780892, 0.5671108 , 0.03243512, ..., 0.7961796 ,
         0.6915286 , 0.31432104],
        [0.55854335, 0.64108146, 0.06840293, ..., 0.03025246,
         0.74772686, 0.76843557],
        ...,
        [0.07398043, 0.72722677, 0.91979166, ..., 0.80485262,
         0.9522405 , 0.40271092],
        [0.63511948, 0.20005061, 0.24026617, ..., 0.88841413,
         0.62129113, 0.2795628 ],
        [0.28390962, 0.20488339, 0.65861717, ..., 0.82808052,
         0.78179691, 0.07502178]],

       [[0.2263334 , 0.2096271 , 0.48325394, ..., 0.08457282,
         0.7263416 , 0.55523118],
        [0.90463941, 0.09186852, 0.09086655, ..., 0.85131925,
         0.44207479, 0.31902093],
        [0.71976767, 0.63443473, 0.80122098, ..., 0.85637951,
         0.79867766, 0.73789999],
        ...,
        [0.08334082, 0.00226663, 0.62297917, ..., 0.25894953,
         0.38934515, 0.93652307],
        [0.8

In [4]:
from tensorly.decomposition import parafac
factors = parafac(tensor, rank=5)
len(factors)

2

In [5]:
factors

(weights, factors) : rank-5 CPTensor of shape (10, 12, 14)

In [6]:
factors[0]

array([1., 1., 1., 1., 1.])

In [7]:
factors[1]

[array([[ 6.41059691, -0.04577301,  0.33030594, -0.31322797,  0.43528802],
        [ 6.63262795,  0.66597393, -0.29196905, -0.06163253, -0.03273339],
        [ 5.82193488, -0.58170178,  0.67134832,  0.57970622, -0.70789269],
        [ 6.64898648, -0.54327623,  0.85141307,  0.60617682, -0.52234249],
        [ 6.17336459, -0.71373045,  0.24820302,  0.23200925, -0.01133236],
        [ 6.28447397, -0.38254169,  0.29459815, -0.80882577, -0.20086888],
        [ 6.17398745, -0.94701231,  0.66696308,  0.40053309,  0.07025056],
        [ 6.83665239,  0.68529381, -0.78769155,  0.24597062, -0.07871664],
        [ 5.64082146,  0.83213946, -0.98042203, -0.54794427, -1.23234452],
        [ 6.54944997,  0.9576944 , -1.03080818,  0.18605605, -0.65974083]]),
 array([[ 0.2947862 ,  0.35027276, -0.56936352,  0.23950495,  0.64584796],
        [ 0.28935455,  0.19131279,  0.09134959,  0.18216068, -0.64562777],
        [ 0.2926491 ,  0.44379021, -0.16010634,  0.38684878, -0.01816023],
        [ 0.31177169,  

In [8]:
A = factors[1][0]
B = factors[1][1]
C = factors[1][2]

In [9]:
C

array([[ 0.26663291,  0.29183942, -0.33702041,  0.53046492, -0.06705147],
       [ 0.26388181, -0.47287374,  0.13851517, -0.50701459, -0.11793685],
       [ 0.2687296 ,  0.07670862, -0.23697555,  0.46803882,  0.32211324],
       [ 0.27451524,  0.29911871, -0.46102514,  0.09374881, -0.21635492],
       [ 0.26635169, -0.07141073,  0.18339078, -0.16329667,  0.31199918],
       [ 0.27212354,  0.17879857, -0.33078482,  0.3767337 , -0.36614993],
       [ 0.28041927, -0.56995378,  0.44620685, -0.7079937 , -0.2395351 ],
       [ 0.25371977,  0.33157123, -0.51068856, -0.40373213,  0.15447579],
       [ 0.27343736, -0.44336596,  0.5454982 , -0.11470511,  0.13760606],
       [ 0.26090049,  0.2718824 , -0.53418747, -0.50762834, -0.37416538],
       [ 0.25279496,  0.27403341, -0.37672794, -0.00763897,  0.21892145],
       [ 0.27989275, -0.49448299,  0.56537409,  0.12970175, -0.10639661],
       [ 0.26296018, -0.41834693,  0.48762961,  0.34478856,  0.53587777],
       [ 0.24403225,  0.57397742, -0.3

In [10]:
from tensorly.tenalg import khatri_rao
CB_khatri_rao = khatri_rao([C, B])
X_mode1 = tl.unfold(tensor, mode=0)
X_approx_mode1 = np.dot(A, CB_khatri_rao.T)

In [11]:
# print results

print("Original tensor (unfolded along mode-1):")
print(X_mode1)

print("\nApproximated tensor (unfolded along mode-1):")
print(X_approx_mode1)

Original tensor (unfolded along mode-1):
[[0.23970169 0.72498048 0.20989424 ... 0.82808052 0.78179691 0.07502178]
 [0.2263334  0.2096271  0.48325394 ... 0.40724019 0.2209723  0.64608514]
 [0.86700999 0.50937207 0.75325941 ... 0.05165329 0.6306222  0.14147317]
 ...
 [0.13924399 0.97929327 0.14265388 ... 0.83284295 0.6103948  0.72097564]
 [0.11264242 0.94246198 0.00768763 ... 0.43045497 0.83474687 0.6740085 ]
 [0.08563646 0.1043511  0.30134752 ... 0.40852789 0.89577972 0.22658432]]

Approximated tensor (unfolded along mode-1):
[[0.50392793 0.47043874 0.44836543 ... 0.54027124 0.32181217 0.35553878]
 [0.52696277 0.55051608 0.57535526 ... 0.68212824 0.35834777 0.37981515]
 [0.63126833 0.42139622 0.53327022 ... 0.27840723 0.51441996 0.55313501]
 ...
 [0.49092318 0.6103302  0.6300959  ... 0.59752708 0.50926324 0.47097949]
 [0.32405163 0.40554566 0.3810808  ... 0.54906767 0.6142884  0.39166724]
 [0.46709311 0.57992347 0.61684473 ... 0.62310759 0.56030167 0.47077577]]


In [12]:
print("\nAre the original and approximated matricized tensors close?")
print(np.allclose(X_mode1, X_approx_mode1, rtol=1, atol=1))


Are the original and approximated matricized tensors close?
True


In [13]:
tensor_approx = tl.kruskal_to_tensor(factors)

error_frobenius_norm = error = tl.norm(tensor - tensor_approx)

print(f"Frobenius norm of the error: {error_frobenius_norm}")

Frobenius norm of the error: 10.830639304075135
