In [13]:
import numpy as np
import pandas as pd
import tensorly as tl
from tensorly.cp_tensor import cp_to_tensor
from tensorly import random
import random
np.random.seed(42)

In [14]:
I = 3
J = 3
K = 3
rank = 2
tensor = tl.tensor(np.random.random((I, J, K)))

In [15]:
tensor

array([[[0.37454012, 0.95071431, 0.73199394],
        [0.59865848, 0.15601864, 0.15599452],
        [0.05808361, 0.86617615, 0.60111501]],

       [[0.70807258, 0.02058449, 0.96990985],
        [0.83244264, 0.21233911, 0.18182497],
        [0.18340451, 0.30424224, 0.52475643]],

       [[0.43194502, 0.29122914, 0.61185289],
        [0.13949386, 0.29214465, 0.36636184],
        [0.45606998, 0.78517596, 0.19967378]]])

In [16]:
from tensorly.decomposition import parafac
factors = parafac(tensor, rank=rank)
len(factors)

2

In [17]:
factors

(weights, factors) : rank-2 CPTensor of shape (3, 3, 3)

In [18]:
factors[0]

array([1., 1.])

In [19]:
factors[1]

[array([[ 1.91806024, -0.31836078],
        [ 0.72470286, -0.57413411],
        [ 1.19833152, -0.30627604]]),
 array([[0.61735235, 0.89854873],
        [0.19185914, 0.61064806],
        [0.6821388 , 0.34990077]]),
 array([[-0.03336264, -1.69700109],
        [ 0.76623608,  0.30500569],
        [ 0.3190305 , -1.21354927]])]

In [20]:
A = factors[1][0]
B = factors[1][1]
C = factors[1][2]

In [21]:
C

array([[-0.03336264, -1.69700109],
       [ 0.76623608,  0.30500569],
       [ 0.3190305 , -1.21354927]])

In [22]:
# Reconstruct tensor from the given particle
reconstructed_tensor = cp_to_tensor((np.ones(rank), [A, B, C]))

reconstructed_tensor

array([[[ 4.45943334e-01,  8.20063954e-01,  7.24921227e-01],
        [ 3.17630494e-01,  2.22677827e-01,  3.53324129e-01],
        [ 1.45385778e-01,  9.68554492e-01,  5.52597122e-01]],

       [[ 8.60535264e-01,  1.85463116e-01,  7.68788165e-01],
        [ 5.90319426e-01, -3.94997428e-04,  4.69821227e-01],
        [ 3.24417745e-01,  3.17514645e-01,  4.01501948e-01]],

       [[ 4.42339964e-01,  4.82917145e-01,  5.69990014e-01],
        [ 3.09714371e-01,  1.19121735e-01,  3.00314901e-01],
        [ 1.54589630e-01,  5.93656844e-01,  3.90836095e-01]]])

In [23]:
# Compute the Frobenius norm of the difference
error = tl.norm(tensor - reconstructed_tensor)
error

0.8625425844610721

In [24]:
"""from tensorly.tenalg import khatri_rao
CB_khatri_rao = khatri_rao([C, B])
X_mode1 = tl.unfold(tensor, mode=0)
X_approx_mode1 = np.dot(A, CB_khatri_rao.T)

# print results

print("Original tensor (unfolded along mode-1):")
print(X_mode1)

print("\nApproximated tensor (unfolded along mode-1):")
print(X_approx_mode1)

print("\nAre the original and approximated matricized tensors close?")
print(np.allclose(X_mode1, X_approx_mode1, rtol=1, atol=1))

tensor_approx = tl.kruskal_to_tensor(factors)

error_frobenius_norm = error = tl.norm(tensor - tensor_approx)

print(f"Frobenius norm of the error: {error_frobenius_norm}")"""

'from tensorly.tenalg import khatri_rao\nCB_khatri_rao = khatri_rao([C, B])\nX_mode1 = tl.unfold(tensor, mode=0)\nX_approx_mode1 = np.dot(A, CB_khatri_rao.T)\n\n# print results\n\nprint("Original tensor (unfolded along mode-1):")\nprint(X_mode1)\n\nprint("\nApproximated tensor (unfolded along mode-1):")\nprint(X_approx_mode1)\n\nprint("\nAre the original and approximated matricized tensors close?")\nprint(np.allclose(X_mode1, X_approx_mode1, rtol=1, atol=1))\n\ntensor_approx = tl.kruskal_to_tensor(factors)\n\nerror_frobenius_norm = error = tl.norm(tensor - tensor_approx)\n\nprint(f"Frobenius norm of the error: {error_frobenius_norm}")'